[package]
name = "aoc2020"
version = "0.1.0"
["Maciej Krzywda <maciej.krzywdaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"
