[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Maciej Krzywda <maciej.krzywdaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
regex = "1.4.2"
rayon = "1.5.0"
itertools = "0.9.0"
modinverse = "0.1.0"

[[bin]]
name = "main"
path = "src/main.rs"
